package Enums;

public enum MessageType {
    HandleCollision ,
    HasCollision,
    Destroy,
    ActivateTopCollision ,
    ActivateBottomCollision,
    DeactivateBottomCollision,
    IsOnLadder,
    IsNoLongerOnLadder,
    LeftCollision,
    RightCollision,
    LeftCollisionWithOther,
    RightCollisionWithOther,
    EnemyDeath,
    Attack,
    PlayerDeath,
    ReadyToBeOpened,
    SpawnGun,
    IsPickedUp,
    LaunchBullet,
    PLayerDirectionRight,
    PlayerDirectionLeft,
    BulletLaunchRight,
    BulletLauchLeft,
    HideGun,
    ShowGun,
    Shoot
}
