package Enums;

/**
 * THis class has all the scene names.
 */
public enum SceneType {
    NO_SCENE, PLAY_SCENE, LEVEL_COMPLETED_SCENE, LEVEL_PAUSED_SCENE, LEVEL_FAILED_SCENE,
    CHOOSE_LEVEL_SCENE, CHOOSE_PLAYER_SCENE, MAIN_MENU_SCENE, LOAD_SCENE
}
